apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Labels to add to all resources and selectors.
commonLabels:
  app: apicurito

resources:
- ../rbac
- ../manager
- ../crd/bases
- ../samples
- ../scorecard
