apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurito-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apicurito-operator
      app: apicurito
  template:
    metadata:
      labels:
        name: apicurito-operator
        app: apicurito
    spec:
      serviceAccountName: apicurito
      containers:
        - name: apicurito-operator
          image: apicurio/apicurito-operator:v0.1
          command:
          - apicurito
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "apicurito-operator"
