apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurito-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicurito
      name: apicurito-operator
  strategy: {}
  template:
    metadata:
      labels:
        app: apicurito
        name: apicurito-operator
    spec:
      containers:
      - env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RELATED_IMAGE_APICURITO_OPERATOR
          value: registry.redhat.io/fuse7-tech-preview/fuse-apicurito-operator:1.6
        - name: RELATED_IMAGE_APICURITO
          value: apicurio/apicurito-ui:latest
        - name: RELATED_IMAGE_GENERATOR
          value: apicurio/fuse-apicurito-generator:latest
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: apicurito-operator
        image: registry.redhat.io/fuse7-tech-preview/fuse-apicurito-operator:1.6
        imagePullPolicy: Always
        name: apicurito-operator
        resources: {}
      serviceAccountName: apicurito
