apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurito-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicurito
      name: apicurito-operator
  strategy: {}
  template:
    metadata:
      labels:
        app: apicurito
        com.company: Red_Hat
        name: apicurito-operator
        rht.comp: Fuse
        rht.comp_ver: "7.8"
        rht.prod_name: Red_Hat_Integration
        rht.prod_ver: "7.8"
        rht.subcomp: apicurito-operator
        rht.subcomp_t: infrastructure
    spec:
      containers:
      - env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RELATED_IMAGE_APICURITO_OPERATOR
          value: registry.redhat.io/fuse7-tech-preview/fuse-apicurito-operator:1.7
        - name: RELATED_IMAGE_APICURITO
          value: apicurio/apicurito-ui:1.1.1
        - name: RELATED_IMAGE_GENERATOR
          value: apicurio/fuse-apicurito-generator:latest
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: apicurito-operator
        image: registry.redhat.io/fuse7-tech-preview/fuse-apicurito-operator:1.7
        imagePullPolicy: Always
        name: apicurito-operator
        resources: {}
      serviceAccountName: apicurito
