apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurito
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apicurito
  template:
    metadata:
      labels:
        name: apicurito
    spec:
      serviceAccountName: apicurito
      containers:
        - name: apicurito
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - apicurito
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "apicurito"
