apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apicurito
rules:
- apiGroups:
  - console.openshift.io
  resources:
  - consoleyamlsamples
  - consolelinks
  verbs:
  - get
  - create
  - list
  - update
  - delete
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  verbs:
  - update
