operator_manifests:
  manifests_dir: manifests
  enable_digest_pinning: true
  enable_repo_replacements: true
  enable_registry_replacements: true
  repo_replacements:
    - registry: registry.redhat.io
      package_mappings:
        fuse-apicurito-operator-container: fuse7
        fuse-apicurito-openshift-container: fuse7
        fuse-apicurito-generator-openshift-container: fuse7